### ISSUE TITLE
Decoding failing due to wrong image mode being passed to PIL.

### ISSUE THREAD

**Issue by SiriusStarr** [AndreMiras/garden.zbarcam#41]
Spent a couple hours trying to figure out why video displayed fine on my desktop but nothing could decode before finding the following.

In `_detect_qrcode_frame()`, the image to be decoded is generated via the following line:
```python
pil_image = PIL.Image.frombytes(mode=fmt, size=size, data=image_data)
```
where `fmt` is derived from `texture.colorfmt` and `image_data` from `texture.pixels`.

[Per Kivy docs](https://kivy.org/doc/stable/api-kivy.graphics.texture.html), `texture.colorfmt`:

> Can be ‘rgba’ or ‘rgb’, ‘luminance’ or ‘luminance_alpha’. On desktop, additional values are available: ‘red’, ‘rg’.

However, per the same docs, `texture.pixels`:

> Get the pixels texture, in RGBA format only, unsigned byte. The origin of the image is at bottom left.

The format returned by `texture.pixels` will always be RGBA.  If however the format returned by `texture.colorfmt` is e.g. RGB, decoding will fail, as the image will be mangled accordingly.

As such, it should just be changed to
```python
pil_image = PIL.Image.frombytes(mode='RGBA', size=size, data=image_data)
```
since `texture.pixels` is guaranteed to return in that format.  This should work on all platforms (and eliminate the need for the iOS special case in that function as well).

**Comment by SiriusStarr** [comment]
Pull request up, #42 .

**Comment by AndreMiras** [comment]
#42 was merged
